baseURL: "https://kmnemon.github.io/"
title: "科的无流派"
paginate: 5
theme: PaperMod
defaultContentLanguage: "zh-cn"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    zh-cn:
        languageName: "Chinese"
        weight: 1
        menu:
            main:
                - name: 文章
                  url: archives
                  weight: 5
                - name: 未发表
                  url: https://keliu1.wordpress.com/
                  weight: 10
 #               - name: Categories
 #                 url: categories
 #                 weight: 10
 #               - name: Series
 #                 url: series
 #                 weight: 10
                - name: 咖啡
                  url: "about"

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: ""
    author: ""
    # author: ["Me", "You"] # multiple authors

    defaultTheme: light
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    TocOpen: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: true
        title: "科的无流派" # optional default will be site title
        subtitle: ""
        imageUrl: "/avatar.jpg" # optional
        imageTitle: "" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size

    socialIcons:
        - name: Github
          url: "https://github.com/kmnemon"
        - name: Email
          url: "mailto:kmnemon@gmail.com"
        - name: RSS
          url: "index.xml"

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
 #   category: categories
 #   tag: tags
 #   series: series

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        lineNos: true
        # noClasses: false
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
